[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-parser"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.4.0"

[lib]
path = "./parser.rs"

[dependencies]
fallible-iterator = { version = "0.1.6", optional = true }
gimli = { version = "0.16.1", optional = true }
object = { version = "0.11.0", optional = true }
parity-wasm = "0.36.0"
typed-arena = { version = "1.4.0", optional = true }
twiggy-ir = { version = "=0.4.0", path = "../ir" }
twiggy-traits = { version = "=0.4.0", path = "../traits" }

[features]
default = ["dwarf"]
dwarf = ["fallible-iterator", "gimli", "object", "typed-arena", "twiggy-traits/dwarf"]
