[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-traits"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.4.0"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.5"
gimli = { version = "0.17.0", optional = true }
wasmparser = "0.29.2"
twiggy-ir = { version = "=0.4.0", path = "../ir" }
csv = "1.0.5"
regex = "1.1.0"

[features]
default = []
dwarf = ["gimli"]
emit_json = []
emit_csv = []
emit_text = []
