[package]
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]
categories = []
description = "Common traits for the Twiggy code size profiler."
license = "Apache-2.0/MIT"
name = "twiggy-traits"
readme = "../README.md"
repository = "https://github.com/rustwasm/twiggy"
version = "0.7.0"
edition = "2018"

[lib]
path = "./traits.rs"

[dependencies]
failure = "0.1.8"
gimli = { version = "0.26.1", optional = true, default-features = false, features = ["std", "read"] }
wasmparser = "0.86.0"
twiggy-ir = { version = "=0.7.0", path = "../ir" }
csv = "1.1.6"
regex = "1.4.2"

[features]
default = []
dwarf = ["gimli"]
emit_json = []
emit_csv = []
emit_text = []
